package padcms.dao.application.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Revision {

	private Long id;
	private String title;
	private String state;
	private Long issue_id;
	private String cover_image_list;
	private String created;
	private String video;
	private String color;
	private String horizontal_mode;
	private String help_page_horizontal;
	private String help_page_vertical;
	private Issue parenIssue;

	public Revision(Long id, String title, String state, Long issue_id,
			String cover_image_list, String created, String video,
			String color, String horizontal_mode, String help_page_horizontal,
			String help_page_vertical) {
		super();
		this.id = id;
		this.title = title;
		this.state = state;
		this.issue_id = issue_id;
		this.cover_image_list = cover_image_list;
		this.created = created;
		this.video = video;
		this.horizontal_mode = horizontal_mode;
		this.help_page_horizontal = help_page_horizontal;
		this.help_page_vertical = help_page_vertical;
		this.color = color;
	}

	public Revision() {
	}

	public Revision(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getIssue_id() {
		return issue_id;
	}

	public void setIssue_id(Long issue_id) {
		this.issue_id = issue_id;
	}

	public String getCover_image_list() {
		return cover_image_list;
	}

	public void setCover_image_list(String cover_image_list) {
		this.cover_image_list = cover_image_list;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getVideo() {
		return video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public String getHorizontal_mode() {
		return horizontal_mode;
	}

	public void setHorizontal_mode(String horizontal_mode) {
		this.horizontal_mode = horizontal_mode;
	}

	public String getHelp_page_horizontal() {
		return help_page_horizontal;
	}

	public void setHelp_page_horizontal(String help_page_horizontal) {
		this.help_page_horizontal = help_page_horizontal;
	}

	public String getHelp_page_vertical() {
		return help_page_vertical;
	}

	public void setHelp_page_vertical(String help_page_vertical) {
		this.help_page_vertical = help_page_vertical;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Issue getParenIssue() {
		return parenIssue;
	}

	public void setParenIssue(Issue parenIssue) {
		this.parenIssue = parenIssue;
	}

}
