package padcms.dao.issue.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class ElementData {

	private Long id;
	private Long element_id;
	private String type;
	private String value;
	private Long position_id;
    private ElementDataPosition elementDataPosition;
    
	public ElementData() {
	}

	public ElementData(Long id) {
		this.id = id;
	}

	public ElementData(Long id, Long element_id, String type, String value,
			Long position_id) {
		super();
		this.id = id;
		this.element_id = element_id;
		this.type = type;
		this.value = value;
		this.position_id = position_id;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getElement_id() {
		return element_id;
	}

	public void setElement_id(Long element_id) {
		this.element_id = element_id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Long getPosition_id() {
		return position_id;
	}

	public void setPosition_id(Long position_id) {
		this.position_id = position_id;
	}

	public ElementDataPosition getElementDataPosition() {
		return elementDataPosition;
	}

	public void setElementDataPosition(ElementDataPosition elementDataPosition) {
		this.elementDataPosition = elementDataPosition;
	}

	

}
