package padcms.dao.issue.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class ElementDataPosition {

	private Long id;
	private Long start_x;
	private Long start_y;
	private Long end_x;
	private Long end_y;

	public ElementDataPosition() {
	}

	public ElementDataPosition(Long id) {
		this.id = id;
	}

	public ElementDataPosition(Long id, Long start_x, Long start_y, Long end_x,
			Long end_y) {
		super();
		this.id = id;
		this.start_x = start_x;
		this.start_y = start_y;
		this.end_x = end_x;
		this.end_y = end_y;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getStart_x() {
		return start_x;
	}

	public void setStart_x(Long start_x) {
		this.start_x = start_x;
	}

	public Long getStart_y() {
		return start_y;
	}

	public void setStart_y(Long start_y) {
		this.start_y = start_y;
	}

	public Long getEnd_x() {
		return end_x;
	}

	public void setEnd_x(Long end_x) {
		this.end_x = end_x;
	}

	public Long getEnd_y() {
		return end_y;
	}

	public void setEnd_y(Long end_y) {
		this.end_y = end_y;
	}

}