package padcms.dao.issue.bean;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Page {

	private Long id;
	private String title;
	private Long horisontal_page_id;
	private Long template;
	private String machine_name;
	private List<PageImposition> pageImpositions;
	private List<Element> listElemnts;
	private PageHorisontal pageHorisontal;

	public Page() {
	}

	public Page(Long id) {
		this.id = id;
	}

	public Page(Long id, String title, Long horisontal_page_id, Long template,
			String machine_name) {
		super();
		this.id = id;
		this.title = title;
		this.horisontal_page_id = horisontal_page_id;
		this.template = template;
		this.machine_name = machine_name;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getHorisontal_page_id() {
		return horisontal_page_id;
	}

	public void setHorisontal_page_id(Long horisontal_page_id) {
		this.horisontal_page_id = horisontal_page_id;
	}

	public Long getTemplate() {
		return template;
	}

	public void setTemplate(Long template) {
		this.template = template;
	}

	public String getMachine_name() {
		return machine_name;
	}

	public void setMachine_name(String machine_name) {
		this.machine_name = machine_name;
	}

	public List<Element> getListElemnts() {
		return listElemnts;
	}

	public void setListElemnts(List<Element> listElemnts) {
		this.listElemnts = listElemnts;
	}

	public PageHorisontal getPageHorisontal() {
		return pageHorisontal;
	}

	public void setPageHorisontal(PageHorisontal pageHorisontal) {
		this.pageHorisontal = pageHorisontal;
	}

	public List<PageImposition> getPageImpositions() {
		return pageImpositions;
	}

	public void setPageImpositions(List<PageImposition> pageImpositions) {
		this.pageImpositions = pageImpositions;
	}

}
