package padcms.dao.issue.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class PageHorisontal {

	private Long id;
	private String name;
	private String resource;

	public PageHorisontal() {
	}

	public PageHorisontal(Long id) {
		this.id = id;
	}

	public PageHorisontal(Long id, String name, String resource) {
		super();
		this.id = id;
		this.name = name;
		this.resource = resource;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getResource() {
		return resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}


}
