package padcms.dao.issue;

import java.util.ArrayList;

import padcms.dao.DBIssueSession;
import padcms.dao.issue.bean.ElementData;
import padcms.dao.issue.bean.ElementDataPosition;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table NOTE.
 */
public class ElementDataFactory extends AbstractDao<ElementData, Long> {

	public static final String TABLENAME = "element_data";

	public static class Properties {
		public final static Property id = new Property(0, Long.class, "id",
				true, "id");
		public final static Property element_id = new Property(1, Long.class,
				"element_id", false, "element_id");
		public final static Property type = new Property(2, String.class,
				"type", false, "type");
		public final static Property value = new Property(3, String.class,
				"value", false, "value");
		public final static Property position_id = new Property(4, Long.class,
				"position_id", false, "position_id");
	};

	public ElementDataFactory(DaoConfig config) {
		super(config);
	}

	public ElementDataFactory(DaoConfig config, DBIssueSession daoSession) {
		super(config, daoSession);
	}

	// /** Creates the underlying database table. */
	// public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
	// String sql = "CREATE TABLE " + (ifNotExists ? "IF NOT EXISTS " : "")
	// + "'" + TABLENAME + "' (" + "'_id' INTEGER PRIMARY KEY ,"
	// + " 'title' TEXT NOT NULL ," + "'horisontal_page_id' INTEGER NOT NULL ,"
	// + " 'template' INTEGER NOT NULL ,"
	// + " 'application_id' INTEGER NOT NULL ,"
	// + " 'paid' TEXT NOT NULL ," + " 'updated' TEXT NOT NULL ,"
	// + " 'color' TEXT NOT NULL ,"
	// + " 'subscription_type' TEXT NOT NULL" + ");";
	// db.execSQL(sql);
	// }

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'"
				+ TABLENAME + "'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt, ElementData entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}
		stmt.bindLong(2, entity.getElement_id());
		stmt.bindString(3, entity.getType());
		stmt.bindString(4, entity.getValue());
		stmt.bindLong(5, entity.getPosition_id());

	}

	/** @inheritdoc */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public ElementData readEntity(Cursor cursor, int offset) {
		ElementData entity = new ElementData(
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.getLong(offset + 1), cursor.getString(offset + 2),
				cursor.getString(offset + 3), cursor.getLong(offset + 4));
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, ElementData entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
		entity.setElement_id(cursor.getLong(offset + 1));
		entity.setType(cursor.getString(offset + 2));
		entity.setValue(cursor.getString(offset + 3));
		entity.setPosition_id(cursor.getLong(offset + 4));

	}

	@Override
	protected Long updateKeyAfterInsert(ElementData entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(ElementData entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	public ArrayList<ElementData> loadAllByElementID(Long elementID) {
		ArrayList<ElementData> arrayList = new ArrayList<ElementData>();
		ElementDataPositionFactory elementDataPositionFactory = ((DBIssueSession) getSession())
				.getElementDataPositionFactory();

		Cursor cursor = db.query(TABLENAME, getAllColumns(),
				Properties.element_id.columnName + "=?",
				new String[] { String.valueOf(elementID) }, null, null, null);
		if (cursor != null) {
			if (cursor.getCount() > 0) {
				cursor.moveToFirst();
				for (int i = 0; i < cursor.getCount(); i++) {
					ElementData elementData = readEntity(cursor, 0);
					arrayList.add(elementData);
					if (elementData.getPosition_id() != 0) {
						ElementDataPosition elementDataPosition = elementDataPositionFactory
								.load(elementData.getPosition_id());
						elementData.setElementDataPosition(elementDataPosition);
					}
					cursor.moveToNext();
				}
			}
			cursor.close();
		}
		return arrayList;
	}

}
