package padcms.dao.issue;

import java.util.ArrayList;

import padcms.dao.DBIssueSession;
import padcms.dao.issue.bean.Page;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table NOTE.
 */
public class PageFactory extends AbstractDao<Page, Long> {

	public static final String TABLENAME = "page";

	public static class Properties {
		public final static Property id = new Property(0, Long.class, "id",
				true, "id");
		public final static Property title = new Property(1, String.class,
				"title", false, "title");
		public final static Property horisontal_page_id = new Property(2,
				Long.class, "horisontal_page_id", false, "horisontal_page_id");
		public final static Property template = new Property(3, Long.class,
				"template", false, "template");
		public final static Property machine_name = new Property(4,
				String.class, "machine_name", false, "machine_name");

	};

	public PageFactory(DaoConfig config) {
		super(config);
	}

	public PageFactory(DaoConfig config, DBIssueSession daoSession) {
		super(config, daoSession);
	}

	// /** Creates the underlying database table. */
	// public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
	// String sql = "CREATE TABLE " + (ifNotExists ? "IF NOT EXISTS " : "")
	// + "'" + TABLENAME + "' (" + "'_id' INTEGER PRIMARY KEY ,"
	// + " 'title' TEXT NOT NULL ," + "'horisontal_page_id' INTEGER NOT NULL ,"
	// + " 'template' INTEGER NOT NULL ,"
	// + " 'application_id' INTEGER NOT NULL ,"
	// + " 'paid' TEXT NOT NULL ," + " 'updated' TEXT NOT NULL ,"
	// + " 'color' TEXT NOT NULL ,"
	// + " 'subscription_type' TEXT NOT NULL" + ");";
	// db.execSQL(sql);
	// }

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'"
				+ TABLENAME + "'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt, Page entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}
		stmt.bindString(2, entity.getTitle());
		stmt.bindLong(3, entity.getHorisontal_page_id());
		stmt.bindLong(4, entity.getTemplate());
		stmt.bindString(5, entity.getMachine_name());

	}

	/** @inheritdoc */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public Page readEntity(Cursor cursor, int offset) {
		Page entity = new Page(
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.getString(offset + 1), cursor.getLong(offset + 2),
				cursor.getLong(offset + 3), cursor.getString(offset + 4));
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, Page entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
		entity.setTitle(cursor.getString(offset + 1));
		entity.setHorisontal_page_id(cursor.getLong(offset + 2));
		entity.setTemplate(cursor.getLong(offset + 3));
		entity.setMachine_name(cursor.getString(offset + 4));

	}

	@Override
	protected Long updateKeyAfterInsert(Page entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(Page entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	public ArrayList<Page> loadIssuePageCollection() {
		ArrayList<Page> pageCollection = (ArrayList<Page>) loadAll();
		initPageRelations(pageCollection);
		return pageCollection;
	}

	public void initPageRelations(ArrayList<Page> pageCollection) {
		ElementFactory factoryElement = ((DBIssueSession) getSession())
				.getElementFactory();
		PageImpositionFactory pageImpositionFactory = ((DBIssueSession) getSession())
				.getPageImpositionFactory();
		PageHorisontalFactory pageHorisontalFactory = ((DBIssueSession) getSession())
				.getPageHorisontalFactory();

		for (Page page : pageCollection) {
			page.setListElemnts(factoryElement.loadAllByPageID(page.getId()));
			page.setPageHorisontal(pageHorisontalFactory.load(page
					.getHorisontal_page_id()));
			page.setPageImpositions(pageImpositionFactory.loadAllByPageID(page
					.getId()));
		}
	}

}
