package padcms.dao.issue;

import java.util.ArrayList;

import padcms.dao.DBIssueSession;
import padcms.dao.issue.bean.PageImposition;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table NOTE.
 */
public class PageImpositionFactory extends AbstractDao<PageImposition, Long> {

	public static final String TABLENAME = "page_imposition";

	public static class Properties {
		public final static Property id = new Property(0, Long.class, "id",
				true, "id");
		public final static Property page_id = new Property(1, Long.class,
				"page_id", false, "page_id");
		public final static Property is_linked_to = new Property(2, Long.class,
				"is_linked_to", false, "is_linked_to");
		public final static Property position_type = new Property(3,
				String.class, "position_type", false, "position_type");

	};

	public PageImpositionFactory(DaoConfig config) {
		super(config);
	}

	public PageImpositionFactory(DaoConfig config, DBIssueSession daoSession) {
		super(config, daoSession);
	}

	// /** Creates the underlying database table. */
	// public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
	// String sql = "CREATE TABLE " + (ifNotExists ? "IF NOT EXISTS " : "")
	// + "'" + TABLENAME + "' (" + "'_id' INTEGER PRIMARY KEY ,"
	// + " 'title' TEXT NOT NULL ," + "'horisontal_page_id' INTEGER NOT NULL ,"
	// + " 'template' INTEGER NOT NULL ,"
	// + " 'application_id' INTEGER NOT NULL ,"
	// + " 'paid' TEXT NOT NULL ," + " 'updated' TEXT NOT NULL ,"
	// + " 'color' TEXT NOT NULL ,"
	// + " 'subscription_type' TEXT NOT NULL" + ");";
	// db.execSQL(sql);
	// }

	/** Drops the underlying database table. */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'"
				+ TABLENAME + "'";
		db.execSQL(sql);
	}

	/** @inheritdoc */
	@Override
	protected void bindValues(SQLiteStatement stmt, PageImposition entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}
		stmt.bindLong(2, entity.getPage_id());
		stmt.bindLong(3, entity.getIs_linked_to());
		stmt.bindString(4, entity.getPosition_type());
	}

	/** @inheritdoc */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/** @inheritdoc */
	@Override
	public PageImposition readEntity(Cursor cursor, int offset) {
		PageImposition entity = new PageImposition(
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.getLong(offset + 1), cursor.getLong(offset + 2),
				cursor.getString(offset + 3));
		return entity;
	}

	/** @inheritdoc */
	@Override
	public void readEntity(Cursor cursor, PageImposition entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor
				.getLong(offset + 0));
		entity.setPage_id(cursor.getLong(offset + 1));
		entity.setIs_linked_to(cursor.getLong(offset + 2));
		entity.setPosition_type(cursor.getString(offset + 3));

	}

	@Override
	protected Long updateKeyAfterInsert(PageImposition entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/** @inheritdoc */
	@Override
	public Long getKey(PageImposition entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/** @inheritdoc */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

	public ArrayList<PageImposition> loadAllByPageID(Long pageID) {
		ArrayList<PageImposition> arrayList = new ArrayList<PageImposition>();
		Cursor cursor = db.query(TABLENAME, getAllColumns(),
				Properties.page_id.columnName + "=?",
				new String[] { String.valueOf(pageID) }, null, null, null);
		if (cursor != null) {
			if (cursor.getCount() > 0) {
				cursor.moveToFirst();
				for (int i = 0; i < cursor.getCount(); i++) {
					PageImposition pageImposition = readEntity(cursor, 0);
					arrayList.add(pageImposition);
					cursor.moveToNext();
				}
			}
			cursor.close();
		}
		return arrayList;
	}

}
